name: Build and Compile Shaders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Update package lists
      - name: Update package lists
        run: sudo apt-get update

      # Install required dependencies for Vulkan SDK
      - name: Install dependencies
        run: |
          sudo apt-get install -y wget software-properties-common
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y libjsoncpp-dev qt5-default

      # Add the LunarG signing key
      - name: Add LunarG signing key
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -

      # Add the Vulkan SDK repository for version 1.3.280 (focal release)
      - name: Add Vulkan SDK repository
        run: |
          echo "deb https://packages.lunarg.com/vulkan/1.3.280/ focal main" | sudo tee /etc/apt/sources.list.d/lunarg-vulkan-1.3.280-focal.list

      # Update package list again after adding the new repository
      - name: Update package list
        run: sudo apt-get update

      # Install Vulkan SDK
      - name: Install Vulkan SDK
        run: |
          sudo apt-get install -y vulkan-sdk

      # Install Vulkan loader
      - name: Install Vulkan loader
        run: |
          sudo apt-get install -y libvulkan-dev

      # Install Vulkan validation layers and SPIR-V tools
      - name: Install Vulkan validation layers
        run: |
          sudo apt-get install -y vulkan-validationlayers-dev spirv-tools

      # Install Vulkan command-line utilities
      - name: Install Vulkan command-line utilities
        run: |
          sudo apt-get install -y vulkan-tools

      # Verify Vulkan installation
      - name: Verify Vulkan SDK installation
        run: vulkaninfo || echo "Vulkan SDK installation failed"

      # Build the project with CMake
      - name: Configure CMake project
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build the project
        run: |
          cd build
          cmake --build .

      # Run shader compilation
      - name: Compile shaders
        run: |
          cd build
          cmake --build . --target Shaders
